### ISSUE TITLE
Reproducing the results from the paper

### ISSUE THREAD

**Issue by rakeshshrestha31** [eriche2016/text2shape.pytorch#1]
Thank you for sharing your code. I was wondering if you were able to replicate the results (recall rate and NDCG) from the paper using this code. I trained on the primitives dataset with your default setting and I get the following results:
```
     k: precision recall recall_rate ndcg
pr @ 1: 0.39601034355374953 0.0011823102665844635 0.39601034355374953 0.39601034355374953
pr @ 2: 0.3853435537495382 0.0023183345000977853 0.5059106021425933 0.3877573883938712
pr @ 3: 0.38326560768377227 0.0034651198002624197 0.578915773919468 0.3857283039467876
pr @ 4: 0.3824806058367196 0.00460141276471635 0.6212596970816402 0.38478633518543603
pr @ 5: 0.38283154783892753 0.005721094601446791 0.657138899150351 0.38471403865053305
```

The RR@1 - 39.60%, RR@2 - 50.59% and NDCG@5 - 38.47% all seem pretty low compared to what is reported in the paper which are all greater than 95%. Did you get similar results? Or am I doing something wrong running your code?

**Comment by rakeshshrestha31** [comment]
Just a reminder in case you missed the previous message

**Comment by eriche2016** [comment]
Hi, thanks for your attention. It is a pity that I was not able to reproduce the results. Currently, I do not have time to look into the reasons. I recommend you to try the official code, which is in TensorFlow.

**Comment by rakeshshrestha31** [comment]
Thank you for the clarification. I will try the official code
